# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MVVM_Swinject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_Swinject
	pod 'RxSwift'
	pod 'RxCocoa'
	pod 'Swinject'

  target 'MVVM_SwinjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
